### ISSUE TITLE
[Heat] Wrong Directory

### ISSUE THREAD

**Issue by aryulianto** [utianayuba/liberty_leap42.1#1]
- Line 274 
`cat /root/heat_template.yml` 
- Line 277 
`heat stack-create -f /root/heat_template.yml -P "ImageID=cirros;NetID=$NET_ID" stack`

to
 
- Line 274 
`cat /root/controller/root/heat_template.yml`
- Line 277 
`heat stack-create -f /root/controller/root/heat_template.yml -P "ImageID=cirros;NetID=$NET_ID" stack`

`

**Comment by utianayuba** [comment]
Hi @aryulianto,
Already added this copy command before that 2 command:
`cp root/heat_template.yml /root/heat_template.yml`

Thanks
